// Copyright Epic Games, Inc. All Rights Reserved.

#include "/Engine/Public/Platform.ush"


uint ClearValue;

void ClearPS(
#if PERMUTATION_OUTPUT_FORMAT == 0
	out uint OutColor : SV_Target0
#elif PERMUTATION_OUTPUT_FORMAT == 1
	out uint2 OutColor : SV_Target0
#endif
)
{
#if PERMUTATION_OUTPUT_FORMAT == 0
	OutColor = ClearValue;
#elif PERMUTATION_OUTPUT_FORMAT == 1
	OutColor = ClearValue.xx;
#endif
}